#!/bin/sh
#
# Configure the remote access parameters
#
# Configuration file is expected to exist at /mnt/external/REMOTE. 
#
# The file must contain the remote access key:
#
#     KEY='AAAAB3NzaC1yc2EAAAADAQABAAABAQCdxhg....'
#
# The file may contain any of the following optional variables:
#
#     PORT='revssh port'
#     NAME='hostname'
#     HOST='revssh server hostname'
#
# This file is part of rxOS.
# rxOS is free software licensed under the
# GNU GPL version 3 or any later version.
#
# (c) 2016 Outernet Inc
# Some rights reserved.

CONF_FILE_EXT="/mnt/external/REMOTE"
CONF_FILE_EXT_DISABLE="/mnt/external/REMOTE_DISABLE"
CONF_FILE="/mnt/conf/REMOTE"
CONF_FILE_DISABLE="/mnt/conf/REMOTE.disabled"


configure_hostname() {
  echo "$NAME" > /etc/hostname
  hostname "$NAME"
}

setup() {
  . "$CONF_FILE"
  [ -n "$NAME" ] && configure_hostname
  [ -z "$KEY" ] && return 1
  echo "$KEY" | base64 -d > /etc/remote_key
  HOST="${HOST:=hub.outernet.is}"
  PORT="${PORT:=$(( RANDOM % 10000 + 20000  ))}"
  echo "REVSSH_HOST=\"$HOST\"" > /etc/conf.d/remote
  echo "REVSSH_PORT=\"$PORT\"" >> /etc/conf.d/remote
  return 0
}

# import external REMOTE config to onboard storage
import_ext() {
  printf "Looking for new configuration: "
  if [ -f "$CONF_FILE_EXT" ]; then
    cp "$CONF_FILE_EXT"  "$CONF_FILE"
    echo "FOUND"
  else
    echo "NONE"
  fi
}

# if $CONF_FILE_EXT_DISABLE file exists, remove CONF_FILE from
# onboard storage to disable remote mode.
check_disable_ext() {
  printf "Looking for external disable: "
  if [ -f "$CONF_FILE_EXT_DISABLE" ]; then
    mv "$CONF_FILE" "$CONF_FILE_DISABLE"
    echo "FOUND"
    # exit early as REMOTE_DISABLE overrides REMOTE
    exit 0
  else
    echo "NONE"
  fi
}

start() {
  # check for external disable
  check_disable_ext
  # import if new external STA config file exists
  import_ext
  printf "Start remote session configuration: "
  if [ -f "$CONF_FILE" ]; then
    setup
    echo "OK"
  else
    echo "DISABLED"
    exit 0
  fi
}

case "$1" in
  start)
    start
    ;;
  *)
    echo "Usage: $0 start"
esac

exit $?
