#!/bin/bash

# for uboot and ramfsinit
export SOURCE_DATE_EPOCH=1451606400

# for kernel and gen_initramfs
export KBUILD_BUILD_TIMESTAMP=2016-01-01
export KBUILD_BUILD_VERSION=1

# for busybox config
export KCONFIG_NOTIMESTAMP=1

# for mkuser
export MKPASSWD_SALT=mgfYRgrU

# for build timestamps
export RXOS_TIMESTAMP="$(date -u --rfc-3339=seconds)"

[ -d rxos/overlays ] || mkdir rxos/overlays/
cp ../overlay-starsdr/overlay-starsdr-3.0.sqfs rxos/overlays/

make BOARD=chip \
    RXOS_TIMESTAMP=$RXOS_TIMESTAMP \
    MKPASSWD_SALT=$MKPASSWD_SALT \
    KCONFIG_NOTIMESTAMP=$KCONFIG_NOTIMESTAMP \
    KBUILD_BUILD_VERSION=$KBUILD_BUILD_VERSION \
    KBUILD_BUILD_TIMESTAMP=$KBUILD_BUILD_TIMESTAMP \
    SOURCE_DATE_EPOCH=$SOURCE_DATE_EPOCH \
    build release-flash
