#!/bin/sh
#
# Stops the initial LED status.
#
# This file is part of rxOS.
# rxOS is free software licensed under the
# GNU GPL version 3 or any later version.
#
# (c) 2016 Outernet Inc
# Some rights reserved.

. /usr/lib/led_ctrl.sh

reset_led() {
  sleep 60
  led_on
}

case "$1" in
  start)
    led_very_slow_blink
    reset_led &
    ;;
  stop)
    led_off
    ;;
  *)
    usage "$0 {start|stop}"
esac
