################################################################################
#
# network-config
#
################################################################################

NETWORK_CONFIG_VERSION = 1.0
NETWORK_CONFIG_LICENSE = GPL
NETWORK_CONFIG_SITE = $(BR2_EXTERNAL)/local/network-config/src
NETWORK_CONFIG_SITE_METHOD = local

NETWORK_CONFIG_AP_IF = $(call qstrip,$(BR2_NETWORK_CONFIG_AP_IF))
NETWORK_CONFIG_DHCP_START = $(call qstrip,$(BR2_NETWORK_CONFIG_DHCP_START))
NETWORK_CONFIG_DHCP_END = $(call qstrip,$(BR2_NETWORK_CONFIG_DHCP_END))
NETWORK_CONFIG_DHCP_NETMASK = $(call qstrip,$(BR2_NETWORK_CONFIG_NETMASK))

NETWORK_CONFIG_AP_IP = $(call qstrip,$(BR2_NETWORK_CONFIG_AP_IP))
NETWORK_CONFIG_IFACES = $(NETWORK_CONFIG_AP_IF)
NETWORK_CONFIG_DHCP_IFACES = $(NETWORK_CONFIG_AP_IF)
NETWORK_CONFIG_DHCP_RANGES = $(NETWORK_CONFIG_AP_IF),$(NETWORK_CONFIG_DHCP_START),$(NETWORK_CONFIG_DHCP_END),$(NETWORK_CONFIG_DHCP_NETMASK)
NETWORK_CONFIG_ALIASES = /\#/$(NETWORK_CONFIG_AP_IP)

ifeq ($(BR2_PACKAGE_NETWORK_CONFIG),y)
PERSISTENT_CONF_LIST += /etc/hostname
PERSISTENT_CONF_LIST += /etc/dropbear
PERSISTENT_CONF_LIST += /etc/hostapd.conf
PERSISTENT_CONF_LIST += /run/dnsmasq.leases
endif

ifeq ($(BR2_NETWORK_CONFIG_HAS_ETH),y)
NETWORK_CONFIG_IFACES += eth0
define NETWORK_CONFIG_INSTALL_ETH
	$(INSTALL) -Dm755 $(@D)/ifplugd.action $(TARGET_DIR)/etc/ifplugd.action
	$(INSTALL) -Dm755 $(@D)/dhcpcfg $(TARGET_DIR)/usr/sbin/dhcpcfg
endef
endif # BR2_NETWORK_CONFIG_HAS_ETH

ifeq ($(BR2_NETWORK_CONFIG_WLAN_NOPOWERSAVE),y)
define NETWORK_CONFIG_INSTALL_NOPOWERSAVE
	$(INSTALL) -Dm755 $(@D)/wlan_powersave.sh \
		$(TARGET_DIR)/usr/sbin/wlan_powersave.sh
	$(INSTALL) -Dm644 $(@D)/99-wifi.rules \
		$(TARGET_DIR)/etc/udev/rules.d/99-wifi.rules
endef
endif # BR2_NETWORK_CONFIG_WLAN_NOPOWERSAVE

ifeq ($(BR2_NETWORK_CONFIG_HAS_GETH),y)
NETWORK_CONFIG_IFACES += usb0
NETWORK_CONFIG_DHCP_IFACES += usb0
NETWORK_CONFIG_ALIASES += /$(call qstrip,$(BR2_NETWORK_CONFIG_GETH_HOSTNAME))/$(call qstrip,$(BR2_NETWORK_CONFIG_GETH_IP))
NETWORK_CONFIG_GETH_DHCP_START = $(call qstrip,$(BR2_NETWORK_CONFIG_GETH_DHCP_START))
NETWORK_CONFIG_GETH_DHCP_END = $(call qstrip,$(BR2_NETWORK_CONFIG_GETH_DHCP_END))
NETWORK_CONFIG_DHCP_RANGES += usb0,$(NETWORK_CONFIG_GETH_DHCP_START),$(NETWORK_CONFIG_GETH_DHCP_END),$(NETWORK_CONFIG_DHCP_NETMASK)
endif # BR2_NETWORK_CONFIG_HAS_GETH

NETWORK_CONFIG_DHCP_CFG = $(foreach cfg,$(NETWORK_CONFIG_DHCP_IFACES),\ninterface=$(cfg))
NETWORK_CONFIG_ALIAS_CFG = $(foreach cfg,$(NETWORK_CONFIG_ALIASES),\naddress=$(cfg))
NETWORK_CONFIG_RANGE_CFG = $(foreach cfg,$(NETWORK_CONFIG_DHCP_RANGES),\ndhcp-range=$(cfg))

NETWORK_CONFIG_SUBS += s|%IFACES%|$(NETWORK_CONFIG_IFACES)|;
NETWORK_CONFIG_SUBS += s|%IFACE%|$(call qstrip,$(BR2_NETWORK_CONFIG_AP_IF))|;
NETWORK_CONFIG_SUBS += s|%SSID%|$(call qstrip,$(BR2_NETWORK_CONFIG_AP_NAME))|;
NETWORK_CONFIG_SUBS += s|%IP%|$(NETWORK_CONFIG_AP_IP)|;
NETWORK_CONFIG_SUBS += s|%GE_IP%|$(call qstrip,$(BR2_NETWORK_CONFIG_GETH_IP))|;
NETWORK_CONFIG_SUBS += s|%NETMASK%|$(NETWORK_CONFIG_DHCP_NETMASK)|;
NETWORK_CONFIG_SUBS += s|%LDIR%|$(call qstrip,$(BR2_NETWORK_CONFIG_DHCP_LDIR))|;
NETWORK_CONFIG_SUBS += s|%DHCP_IFACES%|$(NETWORK_CONFIG_DHCP_CFG)|;
NETWORK_CONFIG_SUBS += s|%ALIASES%|$(NETWORK_CONFIG_ALIAS_CFG)|;
NETWORK_CONFIG_SUBS += s|%RANGES%|$(NETWORK_CONFIG_RANGE_CFG)|;

define NETWORK_CONFIG_INSTALL_TARGET_CMDS
	$(SED) '$(NETWORK_CONFIG_SUBS)' $(@D)/interfaces $(@D)/hostapd.conf \
		$(@D)/dnsmasq.conf

	$(INSTALL) -Dm644 $(@D)/hostapd.conf $(TARGET_DIR)/etc/hostapd.conf
	$(INSTALL) -Dm644 $(@D)/dnsmasq.conf $(TARGET_DIR)/etc/dnsmasq.conf
	$(INSTALL) -Dm755 $(@D)/S81hostapd $(TARGET_DIR)/etc/init.d/S81hostapd
	$(NETWORK_CONFIG_INSTALL_ETH)
	$(NETWORK_CONFIG_INSTALL_NOPOWERSAVE)
endef

$(eval $(generic-package))

# The interfaces file is installed by Buildroot's built-in target finalize 
# hook, so we need to override that with our own built-in hook.
define INSTALL_NETWORK_CONFIG_OVERRIDE
	$(INSTALL) -Dm644 $(NETWORK_CONFIG_DIR)/interfaces \
		$(TARGET_DIR)/etc/network/interfaces
endef

TARGET_FINALIZE_HOOKS += INSTALL_NETWORK_CONFIG_OVERRIDE
