#!/bin/sh
#
# This file is part of rxOS.
# rxOS is free software licensed under the
# GNU GPL version 3 or any later version.
#
# (c) 2016 Outernet Inc
# Some rights reserved.

CHECK_DELAY=5
FAIL_DELAY=200

if_ip() {
    ip addr show dev "$1" | grep "inet " | grep "global" | sed 's/.*inet \([0-9.]*\).*/\1/'
}

guard() {
  while true
  do
    # if wlan0 has no ip
    if [ -z $(if_ip wlan0) ]
    then
        # wait a moment
        sleep $FAIL_DELAY
        # check again
        if [ -z $(if_ip wlan0) ]
        then
            # if still no ip, switch back to ap mode
            setconf netConf.mode ap
            /usr/sbin/netrestart
        fi
    fi
  sleep $CHECK_DELAY
  done
}

start() {
  printf "Starting network guard: "
  guard &
  echo "OK"
}

stop() {
  echo "Nothing to stop."
}


case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
esac

exit $?
