#!/bin/sh
#
# Start all init scripts in /etc/init.d executing them in lexical order.
#
# This file is part of rxOS.
# rxOS is free software licensed under the
# GNU GPL version 3 or any later version.
#
# (c) 2016 Outernet Inc
# Some rights reserved.

. /etc/profile

for script in /etc/init.d/S??*; do
  [ -f "$script" ] || continue
  $script start
done
