#!/bin/sh
#
# Create a MOTD file from platform and version information
#
# This file is part of rxOS.
# rxOS is free software licensed under the 
# GNU GPL version 3 or any later version.
#
# (c) 2016 Outernet Inc
# Some rights reserved.

MOTD_RELEASE_FILE=/etc/platform-release
MOTD_FILE=/etc/motd

. "$MOTD_RELEASE_FILE"

case $1 in
  start)
    echo "============================================" > $MOTD_FILE
    echo "Skylark v$RXOS_VERSION / $RXOS_SUBPLATFORM ($RXOS_BUILD)" >> $MOTD_FILE
    echo "built at $RXOS_TIMESTAMP" >> $MOTD_FILE
    echo >> $MOTD_FILE
    echo "Copyright 2017 Outernet Inc" >> $MOTD_FILE
    echo "Some rights reserved." >> $MOTD_FILE
    echo "============================================" >> $MOTD_FILE
    ;;
  stop)
    ;;
  restart)
    $0 start
    ;;
  *)
    echo "Usage: $* {start|stop|restart}"
    ;;
esac
