#!/bin/sh
#
# start a user script at boot end
#
# This file is part of rxOS.
# rxOS is free software licensed under the
# GNU GPL version 3 or any later version.
#
# (c) 2016 Outernet Inc
# Some rights reserved.

USER_SCRIPT="/boot/bin/user.sh"

case $1 in
  start)
    [ -x "${USER_SCRIPT}" ] && \
    [ $(stat -c "%u" "${USER_SCRIPT}" -eq 0 ] && \
    ${USER_SCRIPT} > /tmp/user.log 2>>&1 &
    ;;
  stop)
    ;;
  restart)
    $0 start
    ;;
  *)
    echo "Usage: $* {start|stop|restart}"
    ;;
esac
