#!/bin/sh
#
# Start and stop the demodulator
#
# This file is part of rxOS.
# rxOS is free software released under the
# GNU GPL version 3 or any later version.
#
# (c) 2016 Outernet Inc
# Some rights reserved.

DAEMON=/usr/sbin/sdr100
PID_FILE=/var/run/sdr.run

. /etc/conf.d/sdr

[ -x "$DAEMON" ] || exit 0
[ -z "$DAEMON_ARGS" ] || exit 0

pre_start() {
  # Unload modules because demod does not like it
  rmmod dvb_usb_rtl28xxu
  rmmod rtl2832
}

start() {
  printf "Starting SDR demodulator: "
  pre_start
  start-stop-daemon start-stop-daemon -S -q -p "$PID_FILE" --exec "$DAEMON" \
    -- $DAEMON_ARGS
  if [ $?  ]; then
    echo "OK"
  else
    echo "FAILED"
  fi
}

stop() {
  printf "Stopping SDR demodulator: "
  start-stop-daemon -K -q -p "$PID_FILE"
  if [ $?  ]; then
    echo "OK"
  else
    echo "FAILED"
  fi
  [ -f "$PID_FILE"  ] && rm "$PID_FILE"
}

restart() {
  stop
  sleep 3
  start
}

reset() {
  [ -f "$PID_FILE" ] || exit 0
  kill -9 "$(cat "$PID_FILE")"
  rm "$PID_FILE"
  sleep 60
  start
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    restart
    ;;
  reset)
    reset
    ;;
  *)
    echo "$0 {start|stop|restart|reset}"
esac

exit $?
