#!/bin/sh
#
# Start and stop the demodulator
#
# This file is part of rxOS.
# rxOS is free software released under the
# GNU GPL version 3 or any later version.
#
# (c) 2016 Outernet Inc
# Some rights reserved.

# Wrapper script params
WRAPPER_SCRIPT="/usr/sbin/demod"
SDR="%BINPATH%"
LIBRARY_PATH="$(dirname "$SDR")"
JSON_PATH="%JSON_PATH%"
PID_FILE=/var/run/sdr.pid
SDR_ARGS="$(/usr/sbin/sdrargs "$JSON_PATH")"

# Daemon params
SCREEN="/usr/bin/screen"
SCREEN_NAME="sdr"
SCREEN_ARGS="-T vt100 -dmS $SCREEN_NAME $WRAPPER_SCRIPT"
RESET_PAUSE=900  # seconds

[ -x "$SDR" ] || exit 0
[ -z "$SDR_ARGS" ] && exit 0

has_session() {
  $SCREEN -list | tail -n +2 | head -n -2 | awk '{print $1}' | cut -d. -f2 \
    grep -q "$SCREEN_NAME"
}

start() {
  printf "Preparing to start SDR demodulator: "
  cat <<EOF > "$WRAPPER_SCRIPT"
#!/bin/sh
LD_LIBRARY_PATH="$LIBRARY_PATH" $SDR $SDR_ARGS
EOF
  chmod +x "$WRAPPER_SCRIPT"
  echo "OK"

  printf "Starting SDR demodulator: "
  $SCREEN $SCREEN_ARGS
  if [ $?  ]; then
    echo "OK"
  else
    echo "FAILED"
  fi
}

stop() {
  printf "Stopping SDR demodulator: "
  $SCREEN -XS "$SCREEN_NAME" quit
  if [ $?  ]; then
    echo "OK"
  else
    echo "FAILED"
  fi
}

restart() {
  stop
  sleep 3
  start
}

reset() {
  has_session || exit 0
  stop
  sleep "$RESET_PAUSE"
  start
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    restart
    ;;
  reset)
    reset
    ;;
  *)
    echo "$0 {start|stop|restart|reset}"
esac

exit $?
