#!/bin/sh
#
# Start and stop the demodulator
#
# This file is part of rxOS.
# rxOS is free software released under the
# GNU GPL version 3 or any later version.
#
# (c) 2016 Outernet Inc
# Some rights reserved.

DAEMON="/usr/bin/screen"
SDR="%BINPATH%"
LIBRARY_PATH="$(dirname "$SDR")"
JSON_PATH="%JSON_PATH%"
PID_FILE=/var/run/sdr.pid
WRAPPER_SCRIPT="/usr/sbin/demod"
SDR_ARGS="$(/usr/sbin/sdrargs "$JSON_PATH")"
DAEMON_ARGS="-T vt100 -dmS sdr $WRAPPER_SCRIPT"
RESET_PAUSE=900  # seconds

[ -x "$SDR" ] || exit 0
[ -z "$SDR_ARGS" ] && exit 0

start() {
  printf "Preparing to start SDR demodulator: "
  cat <<EOF > "$WRAPPER_SCRIPT"
#!/bin/sh
LD_LIBRARY_PATH="$LIBRARY_PATH" $SDR $SDR_ARGS
EOF
  chmod +x "$WRAPPER_SCRIPT"
  echo "OK"

  printf "Starting SDR demodulator: "
  start-stop-daemon -Sqmp "$PID_FILE" -x "$DAEMON" -- $DAEMON_ARGS
  if [ $?  ]; then
    echo "OK"
  else
    echo "FAILED"
  fi
}

stop() {
  printf "Stopping SDR demodulator: "
  start-stop-daemon -Kqp "$PID_FILE" -x "$DAEMON"
  if [ $?  ]; then
    echo "OK"
  else
    echo "FAILED"
  fi
  [ -f "$PID_FILE"  ] && rm "$PID_FILE"
}

restart() {
  stop
  sleep 3
  start
}

reset() {
  [ -f "$PID_FILE" ] || exit 0
  kill -9 "$(cat "$PID_FILE")"
  rm "$PID_FILE"
  sleep "$RESET_PAUSE"
  start
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    restart
    ;;
  reset)
    reset
    ;;
  *)
    echo "$0 {start|stop|restart|reset}"
esac

exit $?
