#!/bin/sh
#
# Perform DCHP configuration of the specified interface.
#
# usage: /sbin/dhcpcfg IFNAME STATE
#
# arguments:
#
#   IFNAME    interface name (e.g., eth0)
#   STATE     'up' or 'down'
#
# The script will generate a PID file at /var/run/udhcpc.<IFNAME>.pid
#
# This file is part of rxOS.
# rxOS is free software licensed under the 
# GNU GPL version 3 or any later version.
#
# (c) 2016 Outernet Inc
# Some rights reserved.

IFACE=$1
STATE=$2
DHCP=/sbin/udhcpc
HOSTNAME=$(cat /etc/hostname)
PIDFILE=/var/run/udhcpc.${IFACE}.pid

case "$STATE" in
    up)
        if [ -f $PIDFILE ];
        then
            exit 0
        fi
        $DHCP -x hostname:$HOSTNAME -i $IFACE -p $PIDFILE -S -b
        ;;
    down)
        kill $(cat $PIDFILE)
        ;;
esac
