#!/bin/sh
#
# Executes scripts found in /etc/setup.d.
#
# This file is part of rxOS.
# rxOS is free software licensed under the
# GNU GPL version 3 or any later version.
#
# (c) 2016 Outernet Inc
# Some rights reserved.

SETUP_D=/etc/setup.d
SETUP_LOGS=/var/log/setup


[ -d /mnt/downloads/.log ] || mkdir /mnt/downloads/.log
[ -L /var/log ] && unlink /var/log
ln -s /mnt/downloads/.log /var/log

[ -d "$SETUP_LOGS" ] || mkdir -p "$SETUP_LOGS"

start() {
  printf "Starting setup: "
  for s in "${SETUP_D}/"*.sh; do
    [ ! -x "$s" ] && continue
    logfile="${SETUP_LOGS}/$(basename "$s").log"
    "$s" > "$logfile" 2>&1
    if [ $? -eq 0 ]; then
      printf "."
      rm "$logfile"  # no longer needed
    else
      printf "!"
    fi
  done
  echo " DONE"
}

stop() {
  echo "Nothing to do"
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart|reload)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
