#!/bin/sh
#
# Start ubihealthd at boot

DAEMON="/usr/sbin/ubihealthd"

RESTART_DELAY="2"

start() {
  printf "Starting ubihealthd: "
  $DAEMON  &
  echo "OK"
}

stop() {
  printf "Stopping ubihealthd: "
  # There's no known PID, so we kill them by process list
  for proc in $(ps ax | grep $DAEMON | grep -v grep | awk '{print $1}'); do
    kill "$proc"
  done
  echo "OK"
}

status() {
  ps ax | grep $DAEMON | grep -q -v grep && echo "Running" || echo "Stopped"
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status
        ;;
    restart)
        stop
        sleep $RESTART_DELAY
        start
        ;;
esac

exit $?
